---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
before_install: gem install bundler -v 1.16.3
