---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.0_with_request_store.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.1_with_request_store.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_5.2_with_request_store.gemfile
